### ISSUE TITLE
Preserve folder structure when embedding folder

### ISSUE THREAD

**Issue by leoyoung07** [saucer/saucer-cli#1]
- frontend dist folder structure:
![image](https://user-images.githubusercontent.com/8199708/175252536-35f999c5-7e3a-494f-98cc-6ae94c258481.png)

- after run cmd: `saucer embed "frontend/dist"`

- expected generated code:
![image](https://user-images.githubusercontent.com/8199708/175252869-45d744ea-70e1-40ca-b71b-f02e7694d3f6.png)

- actual generated code:
![image](https://user-images.githubusercontent.com/8199708/175253009-dba85560-45b1-4c23-b05e-76e16ff7c661.png)

**Comment by Curve** [comment]
Fixed by [9f0ffc0](https://github.com/saucer/saucer-cli/commit/9f0ffc00d13478d5d5dc7a12f17f219452a17479).

Saucer now also supports this on Qt with relative paths since [c0c856b](https://github.com/saucer/saucer/commit/c0c856b0333c1632740a92f65f1d54b1551ea1d6) - WebView2 support will hopefully be added later this week ^^

Sorry it took me so long to do this - I must've overlooked the Github Notification / Mail for this issue!
